version: '3.7'
services:
  web:
    container_name: webstore_container
    image: webstore:1.0
    environment: 
      - DBPROVIDER=postgresql
      - DBHOST=db
      - DBNAME=webstoredb
      - DBUSR=manager
      - DBPSW=WebStore2020
      - DBPORT=5432
    ports:
      - 80:5000
    depends_on:
      - db
  db:
    container_name: database_container
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=WebStore2020
      - POSTGRES_DB=webstoredb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
volumes:
  postgres_data: