"""Including token related fields

Revision ID: 913dd39c61d3
Revises: 1cf3728f3ab0
Create Date: 2020-10-24 18:15:30.828291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913dd39c61d3'
down_revision = '1cf3728f3ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###
